personal:
  email: ENC[AES256_GCM,data:z0FB+4GlbVcwbZVilvRFvH4O3+xdIp52Zno=,iv:xq0lMilsYE1UIsAKtj6dFF7Gy5uRzVKjh1xXq4NKRKE=,tag:jPvKqTBebjjG8IVC9Rx+tw==,type:str]
  phone: ENC[AES256_GCM,data:ferUuE3Rt6/Bwg==,iv:ASzqUbGQjpZ8XkH3w8Ki3d1I0M0K5c0S2Ve2oPwLarg=,tag:bwLLrW831WudLCIg43Kc/w==,type:int]
  domain: ENC[AES256_GCM,data:mYaZR+8+M7yby0I=,iv:7mT81/SXl7UjuuXoggFd7XBNS0ukR//7NHzyeLWOZ2Q=,tag:0srs43nmMjaE1yn/J69wtA==,type:str]
  ip: ENC[AES256_GCM,data:DzgNEIdc17ThIkV4/UBD,iv:BKgPa9m7nGQDMOv1FBlb2KCGA5ihONfywnck6sZgH+o=,tag:jFvjpo6v3Mqb8NOZr6LPCQ==,type:str]
fck_nat:
  pub_key: ENC[AES256_GCM,data:+iTFyt7VbNCm8Z1bva2hwIDXpMMuzMbmkoJQtIv1Agr3ajzWgHB7NQhtICF9CPBqxHNSRW6BjoBDRhQ4cQj7dmM06tP206I4dg3G7B0UZZmpSynnKr3dQg==,iv:Yu2p2h3IkUWtXqzfAfzLR9+ekcm6vV1nxnYnbyQpNQE=,tag:uozCqkCCkM+sd8rdLW6TrQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:eu-west-1:266294491328:key/mrk-5e8a3e4923bd4b0d8e19bea688afdfcf
      created_at: "2023-10-31T15:15:07Z"
      enc: AQICAHjX3pwKkQFEYRgeLh0AnFr7ffgKJYzCrrdds16hZz2zWgHXxQZ4CFpTH7cekNWmq43AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM92a+YBRv4kpIB9q+AgEQgDvnVn14HJ6K+qWpsodHFKa/vE7sMv41yJ2ePb1IxMzenyJSPDwdAoExtAn+kXzy3ULbETBKFFZbwYXkzQ==
      aws_profile: ""
  lastmodified: "2026-03-10T16:09:21Z"
  mac: ENC[AES256_GCM,data:Op3/OGh49WXE/nBgjzjzTN+gO6+Lt+dRo6uJZ1EgS6hXMsLBrSwi8BmqNdfxPSz/fjyquXwXXIMXGabiR8Fot0aseNPec54YWFfuL0llIjQHMlBYZr4YI89v1b+rYBe/cFKAWPMiNL5OhUl3Hf+MS10JOTgkYw0xNFjmzmYGvag=,iv:JWr8JAgIiAFOFyG5a9zFMlcdNmEi2TVBBn5QcAh4O08=,tag:9CnZHRTZIaNvE0q2+2/TMA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
