personal:
  email: ENC[AES256_GCM,data:WaXtsDXnU64UjOpDDd3q5O4TnCOTAWLX+Hqp61Owvdw=,iv:aCPDXbV2f/rC+b1//hagZwbAgp+c2czyGjEHMEisUZw=,tag:UlvKM5XtHXpQWQLZG3rEnw==,type:str]
  phone: ENC[AES256_GCM,data:ferUuE3Rt6/Bwg==,iv:ASzqUbGQjpZ8XkH3w8Ki3d1I0M0K5c0S2Ve2oPwLarg=,tag:bwLLrW831WudLCIg43Kc/w==,type:int]
  domain: ENC[AES256_GCM,data:mYaZR+8+M7yby0I=,iv:7mT81/SXl7UjuuXoggFd7XBNS0ukR//7NHzyeLWOZ2Q=,tag:0srs43nmMjaE1yn/J69wtA==,type:str]
  ip: ENC[AES256_GCM,data:DzgNEIdc17ThIkV4/UBD,iv:BKgPa9m7nGQDMOv1FBlb2KCGA5ihONfywnck6sZgH+o=,tag:jFvjpo6v3Mqb8NOZr6LPCQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:eu-west-1:266294491328:key/mrk-5e8a3e4923bd4b0d8e19bea688afdfcf
      created_at: "2023-10-31T15:15:07Z"
      enc: AQICAHjX3pwKkQFEYRgeLh0AnFr7ffgKJYzCrrdds16hZz2zWgHXxQZ4CFpTH7cekNWmq43AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM92a+YBRv4kpIB9q+AgEQgDvnVn14HJ6K+qWpsodHFKa/vE7sMv41yJ2ePb1IxMzenyJSPDwdAoExtAn+kXzy3ULbETBKFFZbwYXkzQ==
      aws_profile: ""
  lastmodified: "2026-03-10T14:14:42Z"
  mac: ENC[AES256_GCM,data:OuHg6X/FKUNdSsXGmqYvXE0O1FaQpruKjdcXCjRh4nuKB3QLKSdfdelPgM8sMtQCqqUby2tTPHqi0MFeMIWJH0Wui7W9qgEENzlT3i6n1OECHLqVYu+zs/cmJ8wXkJKIrHkAKptCzth8tBjkBjMOWGffJwSSyVDVQh7DBe3XjLk=,iv:0PPUfCxlXAlHmznBpafDIGanJUzqGXsAwY6tk3sGOPc=,tag:1tqdMRgby757rUBIHa1Nmw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
