apiVersion: v2
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 82.18.0
    alias: kps
    condition: kps.enabled
  - name: loki
    repository: https://grafana-community.github.io/helm-charts
    version: 6.57.0
    condition: loki.enabled
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.57.5
    alias: fluent
    condition: fluent.enabled
  - name: tempo
    repository: https://grafana-community.github.io/helm-charts
    version: 2.1.2
    condition: tempo.enabled
description: Helm chart managing observability tooling; Prometheus, Alertmanager, LGT(M) + Fluent-bit
name: monitoring
type: application
version: 0.1.0
