{{- $releaseNamespace := .Release.Namespace -}}
{{- range $name, $store := .Values.clusterSecretStores }}
{{- if $store.enabled }}
{{- if hasKey $store.provider.aws.auth.jwt.serviceAccountRef "namespace" }}
{{- $_ := set $store.provider.aws.auth.jwt.serviceAccountRef "namespace" (default $releaseNamespace $store.provider.aws.auth.jwt.serviceAccountRef.namespace) }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
spec:
  provider:
{{ toYaml $store.provider | indent 4 }}
{{- end }}
{{- end }}
