apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  source:
    repoURL: git@github.com:Sean-FC/playground.git
    targetRevision: feat/nginx-cert-manager
    path: argo/charts/cert-manager
    helm:
      valueFiles:
        - values.dev.yaml
