apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds-karpenter
  namespace: argo
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter-crd
    targetRevision: 1.9.0
