apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argo
  annotations:
    argocd-diff-preview/watch-pattern: |
      argo/charts/core/goldilocks/templates/.*,
      argo/charts/core/goldilocks/values.*\.ya?ml,
      argo/charts/core/goldilocks/Chart\.yaml,
      argo/charts/core/goldilocks/Chart\.lock
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: goldilocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  source:
    repoURL: git@github.com:Sean-FC/playground.git
    targetRevision: main
    path: argo/charts/core/goldilocks
    helm:
      valueFiles:
        - values.dev.yaml
