apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
    annotations:
      argocd-diff-preview/watch-pattern: |
        argo/charts/core/keda/templates/.*,
        argo/charts/core/keda/values.*\.ya?ml,
        argo/charts/core/keda/Chart\.yaml,
        argo/charts/core/keda/Chart\.lock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        terminable: "true"
  source:
    repoURL: git@github.com:Sean-FC/playground.git
    targetRevision: main
    path: argo/charts/core/keda
    helm:
      valueFiles:
        - values.dev.yaml
