apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argo
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    annotations:
      argocd-diff-preview/watch-pattern: |
        argo/charts/core/monitoring/templates/.*,
        argo/charts/core/monitoring/values.*\.ya?ml,
        argo/charts/core/monitoring/Chart\.yaml,
        argo/charts/core/monitoring/Chart\.lock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  source:
    repoURL: git@github.com:Sean-FC/playground.git
    targetRevision: main
    path: argo/charts/core/monitoring
    helm:
      valueFiles:
        - values.dev.yaml
