apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argo
spec:
  project: core
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
    annotations:
      argocd-diff-preview/watch-pattern: |
        argo/charts/core/reloader/templates/.*,
        argo/charts/core/reloader/values.*\.ya?ml,
        argo/charts/core/reloader/Chart\.yaml,
        argo/charts/core/reloader/Chart\.lock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:Sean-FC/playground.git
    targetRevision: main
    path: argo/charts/core/reloader
    helm:
      valueFiles:
        - values.dev.yaml
