{{- if and .Values.renovate.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renovate
  labels:
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: renovate
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
