{{- if .Values.generalClusterQueue.enabled }}
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: {{ .Values.generalClusterQueue.name }}
  labels:
    {{- include "kueue.labels" . | nindent 4 }}
spec:
  cohort: {{ .Values.generalClusterQueue.cohortName }}
  namespaceSelector:
    {{- toYaml .Values.generalClusterQueue.namespaceSelector | nindent 4 }}
  flavorFungibility:
    {{- toYaml .Values.generalClusterQueue.flavorFungibility | nindent 4 }}
  resourceGroups:
    - coveredResources:
        - {{ .Values.gpuResource.name }}
      flavors:
{{- range .Values.generalClusterQueue.quotas }}
        - name: {{ .flavor }}
          resources:
            - name: {{ $.Values.gpuResource.name }}
              nominalQuota: {{ .nominalQuota | quote }}
{{- end }}
{{- end }}
