apiVersion: v2
dependencies:
  - name: kuberay-operator
    version: 1.6.0
    repository: https://ray-project.github.io/kuberay-helm/
    condition: kuberay-operator.enabled
description: Helm chart for deploying Ray Services using the KubeRay operator
name: ray
type: application
version: 0.1.0
