{{- if not .Values.operatorOAuthSecret.remoteRef.key }}
{{- fail "operatorOAuthSecret.remoteRef.key must be set" }}
{{- end }}
{{- if .Values.tailscale.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth # required name
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.operatorOAuthSecret.remoteRef.key | quote }}
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.operatorOAuthSecret.remoteRef.key | quote }}
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
