aws-ebs-csi-driver:
  nameOverride: ebs-csi-driver
  controller:
    serviceAccount:
      name: ebs-csi-controller
      annotations:
        eks.amazonaws.com/audience: "sts.amazonaws.com"
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    enableNodeLocalVolumes: true
    serviceMonitor:
      labels:
        release: monitoring
  node:
    enableWindows: false
    tolerations:
      - operator: Exists
        effect: NoExecute
        tolerationSeconds: 120
  storageClasses:
    - name: gp3
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      allowVolumeExpansion: true
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      parameters:
        type: gp3
        csi.storage.k8s.io/fstype: ext4
        encrypted: "true"
