{{- if .Values.sharedSecrets.ecrDocker.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.sharedSecrets.ecrDocker.name }}
spec:
  externalSecretName: {{ .Values.sharedSecrets.ecrDocker.name }}
  refreshTime: {{ .Values.sharedSecrets.ecrDocker.refreshTime }}
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
{{ toYaml .Values.sharedSecrets.ecrDocker.targetNamespaces | indent 12 }}
  externalSecretSpec:
    refreshPolicy: Periodic
    refreshInterval: {{ .Values.sharedSecrets.ecrDocker.refreshInterval }}
    target:
      name: {{ .Values.sharedSecrets.ecrDocker.name }}
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: kubernetes.io/dockerconfigjson
        metadata:
          annotations:
            expiresAt: "{{ `{{ .expires_at }}` }}"
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "{{`{{ .proxy_endpoint | replace "https://" "" }}`}}": {
                  "username": "{{ `{{ .username }}` }}",
                  "password": "{{ `{{ .password }}` }}",
                  "auth": {{ `"{{ printf "%s:%s" .username .password | b64enc }}"` }}
                }
              }
            }
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: {{ .Values.sharedSecrets.ecrDocker.name }}
{{- end }}
