argo-cd:
  crds:
    install: false
  configs:
    cm:
      timeout.reconciliation: 30s
    params:
      server.insecure: true
  controller:
    replicas: 1
  dex:
    enabled: false
  redis:
    enabled: true
  repoServer:
    replicas: 1
    extraArgs:
      - --allow-oob-symlinks
  applicationSet:
    replicas: 1
  notifications:
    enabled: false
  server:
    replicas: 1
    service:
      type: ClusterIP
    ingress:
      enabled: false
      ingressClassName: tailscale
      tls: true
    httproute:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
          sectionName: websecure
  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: core
        namespace: argo
      spec:
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
        sourceRepos:
          - "*"
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: apps # Simple split for now of 'core' charts + 'apps'
        namespace: argo
      spec:
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
        sourceRepos:
          - "*"
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: data
        namespace: argo
      spec:
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
        sourceRepos:
          - "*"
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: ml
        namespace: argo
      spec:
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
        sourceRepos:
          - "*"
updater:
  enabled: false
  fullnameOverride: argocd-image-updater
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  extraArgs:
    - --interval
    - 1m
  config:
    "log.level": "warn"
  podAnnotations: {}
  serviceAccount:
    name: argo-image-updater
    create: true
    annotations:
      eks.amazonaws.com/audience: "sts.amazonaws.com"
