{{- if and .Values.kps.enabled .Values.kps.grafana.enabled .Values.kps.grafana.admin.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kps.grafana.admin.existingSecret }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ .Values.kps.grafana.admin.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.kps.grafana.admin.userKey }}
      remoteRef:
        key: {{ .Values.kps.grafana.admin.externalSecret.remoteRef.key | quote }}
        property: user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: {{ .Values.kps.grafana.admin.passwordKey }}
      remoteRef:
        key: {{ .Values.kps.grafana.admin.externalSecret.remoteRef.key | quote }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
