cert-manager:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::266294491328:role/dev-aws-cert-manager"
clusterIssuer:
  enabled: true
  email: objects-accrual4g@icloud.com
  solvers:
    - selector:
        dnsZones:
          - dev.enervate.io
      dns01:
        route53:
          region: eu-west-1
