crowdsec:
  externalSecret:
    enabled: true
    remoteRef:
      key: "/dev/eso/crowdsec"
  appsec:
    configs:
      oauth2-proxy-callback-allow.yaml: |
        name: custom/oauth2-proxy-callback-allow
        on_match:
          - filter: req.Host == "oauth2-proxy.dev.enervate.io" && req.URL.Path == "/oauth2/callback"
            apply:
              - CancelEvent()
              - CancelAlert()
              - SetRemediation("allow")
  lapi:
    env:
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-secrets
            key: enrollKey
      - name: ENROLL_INSTANCE_NAME
        value: playground-dev
      - name: ENROLL_TAGS
        value: "k8s dev traefik"
      - name: BOUNCER_KEY_traefik
        valueFrom:
          secretKeyRef:
            name: crowdsec-secrets
            key: traefikBouncerKey
