{{- $existingSecret := required "The secret is mandatory for deployment!" .Values.oauth2.config.existingSecret }}
{{- if .Values.oauth2ProxyExternalSecret.remoteRef.key }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $existingSecret }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ $existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.oauth2ProxyExternalSecret.remoteRef.key | quote }}
        property: client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.oauth2ProxyExternalSecret.remoteRef.key | quote }}
        property: client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.oauth2ProxyExternalSecret.remoteRef.key | quote }}
        property: cookie-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
