{{- if and (index .Values "default-scale-set" "enabled") .Values.auth.externalSecret.enabled .Values.auth.externalSecret.remoteRef.key .Values.auth.secretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.auth.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ .Values.auth.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: {{ .Values.auth.externalSecret.remoteRef.key | quote }}
        property: github_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
