{{- if and .Values.crowdsec.bouncer.enabled .Values.crowdsec.bouncer.externalSecret.enabled .Values.crowdsec.bouncer.externalSecret.remoteRef.key }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.crowdsec.bouncer.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ .Values.crowdsec.bouncer.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.crowdsec.bouncer.secretKey }}
      remoteRef:
        key: {{ .Values.crowdsec.bouncer.externalSecret.remoteRef.key | quote }}
        property: traefikBouncerKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
