{{- if and .Values.crowdsec.enabled .Values.crowdsec.externalSecret.enabled .Values.crowdsec.externalSecret.remoteRef.key .Values.crowdsec.secrets.externalSecret.name }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.crowdsec.secrets.externalSecret.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ .Values.crowdsec.secrets.externalSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.crowdsec.secrets.externalSecret.csLapiSecretKey }}
      remoteRef:
        key: {{ .Values.crowdsec.externalSecret.remoteRef.key | quote }}
        property: csLapiSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: {{ .Values.crowdsec.secrets.externalSecret.registrationTokenKey }}
      remoteRef:
        key: {{ .Values.crowdsec.externalSecret.remoteRef.key | quote }}
        property: registrationToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: enrollKey
      remoteRef:
        key: {{ .Values.crowdsec.externalSecret.remoteRef.key | quote }}
        property: enrollKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: traefikBouncerKey
      remoteRef:
        key: {{ .Values.crowdsec.externalSecret.remoteRef.key | quote }}
        property: traefikBouncerKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
