{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "presigner.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  refreshInterval: 24h
  target:
    name: {{ include "presigner.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: BUCKET
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: bucket
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
